import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";

import { AuthProvider } from "@/lib/auth/auth-provider";
import Sidebar from "@/components/layout/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <TooltipProvider delayDuration={0}>
            <div className="grid h-screen w-full pl-[53px]">
              <Sidebar />
              {children}
            </div>
          </TooltipProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
